name: Documentation Check
on: push

jobs:
  build-docs:
    name: Build Docs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@master

      - name: Set up Python 3.x
        uses: actions/setup-python@v1
        with:
          python-version: 3.x

      - name: Install packages
        run: |
          python -m pip install --upgrade pip
          pip install -U poetry twine wheel
          poetry install

      - name: Build docs
        run: |
          mkdir gh-pages
          touch gh-pages/.nojekyll
          cd docs/
          poetry run sphinx-build -b html . _build
          cp -r _build/* ../gh-pages/
