name: Publish 📦 to PyPI
on: push

jobs:
  build-docs:
    name: Build and publish Python distributions to PyPI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@master

      - name: Set up Python 3.x
        uses: actions/setup-python@v1
        with:
          python-version: 3.x

      - name: Install packages
        run: |
          python -m pip install --upgrade pip
          pip install -U poetry twine wheel
          poetry install

      - name: Build docs
        working-directory: ./docs
        run: make html
